services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq-definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: monstrualdb
      POSTGRES_USER: monstrual
      POSTGRES_PASSWORD: example
    ports:
      - 5434:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data 
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
 
volumes:
  pg_data:
  rabbitmq_data: